# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-03-17 01:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190314_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 17, 1, 36, 47, 758677, tzinfo=utc)),
        ),
    ]
